language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t gizzy444/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gizzy444/react-test npm test

  after_success:
    - docker build -t gizzy444/multi-client ./client
    - docker build -t gizzy444/multi-nginx ./nginx
    - docker build -t gizzy444/multi-server ./server
    - docker build -t gizzy444/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push gizzy444/multi-client
    - docker push gizzy444/multi-nginx 
    - docker push gizzy444/multi-server
    - docker push gizzy444/multi-worker
